framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options: { queue_name: emails }
                retry_strategy: { max_retries: 5, delay: 1000, multiplier: 2, max_delay: 60000 }
            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options: { queue_name: failed_emails }
            sync: 'sync://'

        routing:
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': async
            'App\Reminder\Message\SendBookingReminder': async

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
                failed: 'in-memory://'
